// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: tracking.proto

package tracking

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// UpsertRequest 插入或更新追踪数据请求
type UpsertRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TrackingNumber string                 `protobuf:"bytes,1,opt,name=tracking_number,json=trackingNumber,proto3" json:"tracking_number,omitempty"`
	Detail         string                 `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	Status         int32                  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	ServiceClass   string                 `protobuf:"bytes,4,opt,name=service_class,json=serviceClass,proto3" json:"service_class,omitempty"`
	SyncedAt       int64                  `protobuf:"varint,5,opt,name=synced_at,json=syncedAt,proto3" json:"synced_at,omitempty"`
	// tracking_logs 同步字段（时间戳，ISO8601 字符串）
	ReceivedAt    string `protobuf:"bytes,6,opt,name=received_at,json=receivedAt,proto3" json:"received_at,omitempty"`    // 揽收时间（FIRST_MILE_ARRIVE 节点）
	DeliveredAt   string `protobuf:"bytes,7,opt,name=delivered_at,json=deliveredAt,proto3" json:"delivered_at,omitempty"` // 签收时间（DELIVERED 节点）
	TrackedAt     string `protobuf:"bytes,8,opt,name=tracked_at,json=trackedAt,proto3" json:"tracked_at,omitempty"`       // 最后轨迹时间（最后一条事件）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertRequest) Reset() {
	*x = UpsertRequest{}
	mi := &file_tracking_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertRequest) ProtoMessage() {}

func (x *UpsertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tracking_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertRequest.ProtoReflect.Descriptor instead.
func (*UpsertRequest) Descriptor() ([]byte, []int) {
	return file_tracking_proto_rawDescGZIP(), []int{0}
}

func (x *UpsertRequest) GetTrackingNumber() string {
	if x != nil {
		return x.TrackingNumber
	}
	return ""
}

func (x *UpsertRequest) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *UpsertRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UpsertRequest) GetServiceClass() string {
	if x != nil {
		return x.ServiceClass
	}
	return ""
}

func (x *UpsertRequest) GetSyncedAt() int64 {
	if x != nil {
		return x.SyncedAt
	}
	return 0
}

func (x *UpsertRequest) GetReceivedAt() string {
	if x != nil {
		return x.ReceivedAt
	}
	return ""
}

func (x *UpsertRequest) GetDeliveredAt() string {
	if x != nil {
		return x.DeliveredAt
	}
	return ""
}

func (x *UpsertRequest) GetTrackedAt() string {
	if x != nil {
		return x.TrackedAt
	}
	return ""
}

// UpsertResponse 插入或更新响应
type UpsertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertResponse) Reset() {
	*x = UpsertResponse{}
	mi := &file_tracking_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertResponse) ProtoMessage() {}

func (x *UpsertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tracking_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertResponse.ProtoReflect.Descriptor instead.
func (*UpsertResponse) Descriptor() ([]byte, []int) {
	return file_tracking_proto_rawDescGZIP(), []int{1}
}

func (x *UpsertResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpsertResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// GetTrackingRequest 获取追踪数据请求
type GetTrackingRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TrackingNumber string                 `protobuf:"bytes,1,opt,name=tracking_number,json=trackingNumber,proto3" json:"tracking_number,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetTrackingRequest) Reset() {
	*x = GetTrackingRequest{}
	mi := &file_tracking_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTrackingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrackingRequest) ProtoMessage() {}

func (x *GetTrackingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tracking_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTrackingRequest.ProtoReflect.Descriptor instead.
func (*GetTrackingRequest) Descriptor() ([]byte, []int) {
	return file_tracking_proto_rawDescGZIP(), []int{2}
}

func (x *GetTrackingRequest) GetTrackingNumber() string {
	if x != nil {
		return x.TrackingNumber
	}
	return ""
}

// GetTrackingResponse 获取追踪数据响应
type GetTrackingResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TrackingNumber string                 `protobuf:"bytes,1,opt,name=tracking_number,json=trackingNumber,proto3" json:"tracking_number,omitempty"`
	Detail         string                 `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	Status         int32                  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	ServiceClass   string                 `protobuf:"bytes,4,opt,name=service_class,json=serviceClass,proto3" json:"service_class,omitempty"`
	SyncedAt       int64                  `protobuf:"varint,5,opt,name=synced_at,json=syncedAt,proto3" json:"synced_at,omitempty"`
	ErrorMessage   string                 `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetTrackingResponse) Reset() {
	*x = GetTrackingResponse{}
	mi := &file_tracking_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTrackingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrackingResponse) ProtoMessage() {}

func (x *GetTrackingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tracking_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTrackingResponse.ProtoReflect.Descriptor instead.
func (*GetTrackingResponse) Descriptor() ([]byte, []int) {
	return file_tracking_proto_rawDescGZIP(), []int{3}
}

func (x *GetTrackingResponse) GetTrackingNumber() string {
	if x != nil {
		return x.TrackingNumber
	}
	return ""
}

func (x *GetTrackingResponse) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *GetTrackingResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetTrackingResponse) GetServiceClass() string {
	if x != nil {
		return x.ServiceClass
	}
	return ""
}

func (x *GetTrackingResponse) GetSyncedAt() int64 {
	if x != nil {
		return x.SyncedAt
	}
	return 0
}

func (x *GetTrackingResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// MarkErrorRequest 标记错误请求
type MarkErrorRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TrackingNumber string                 `protobuf:"bytes,1,opt,name=tracking_number,json=trackingNumber,proto3" json:"tracking_number,omitempty"`
	ErrorMessage   string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MarkErrorRequest) Reset() {
	*x = MarkErrorRequest{}
	mi := &file_tracking_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkErrorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkErrorRequest) ProtoMessage() {}

func (x *MarkErrorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tracking_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkErrorRequest.ProtoReflect.Descriptor instead.
func (*MarkErrorRequest) Descriptor() ([]byte, []int) {
	return file_tracking_proto_rawDescGZIP(), []int{4}
}

func (x *MarkErrorRequest) GetTrackingNumber() string {
	if x != nil {
		return x.TrackingNumber
	}
	return ""
}

func (x *MarkErrorRequest) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// MarkErrorResponse 标记错误响应
type MarkErrorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkErrorResponse) Reset() {
	*x = MarkErrorResponse{}
	mi := &file_tracking_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkErrorResponse) ProtoMessage() {}

func (x *MarkErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tracking_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkErrorResponse.ProtoReflect.Descriptor instead.
func (*MarkErrorResponse) Descriptor() ([]byte, []int) {
	return file_tracking_proto_rawDescGZIP(), []int{5}
}

func (x *MarkErrorResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *MarkErrorResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_tracking_proto protoreflect.FileDescriptor

const file_tracking_proto_rawDesc = "" +
	"\n" +
	"\x0etracking.proto\x12\btracking\"\x8d\x02\n" +
	"\rUpsertRequest\x12'\n" +
	"\x0ftracking_number\x18\x01 \x01(\tR\x0etrackingNumber\x12\x16\n" +
	"\x06detail\x18\x02 \x01(\tR\x06detail\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status\x12#\n" +
	"\rservice_class\x18\x04 \x01(\tR\fserviceClass\x12\x1b\n" +
	"\tsynced_at\x18\x05 \x01(\x03R\bsyncedAt\x12\x1f\n" +
	"\vreceived_at\x18\x06 \x01(\tR\n" +
	"receivedAt\x12!\n" +
	"\fdelivered_at\x18\a \x01(\tR\vdeliveredAt\x12\x1d\n" +
	"\n" +
	"tracked_at\x18\b \x01(\tR\ttrackedAt\"D\n" +
	"\x0eUpsertResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"=\n" +
	"\x12GetTrackingRequest\x12'\n" +
	"\x0ftracking_number\x18\x01 \x01(\tR\x0etrackingNumber\"\xd5\x01\n" +
	"\x13GetTrackingResponse\x12'\n" +
	"\x0ftracking_number\x18\x01 \x01(\tR\x0etrackingNumber\x12\x16\n" +
	"\x06detail\x18\x02 \x01(\tR\x06detail\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status\x12#\n" +
	"\rservice_class\x18\x04 \x01(\tR\fserviceClass\x12\x1b\n" +
	"\tsynced_at\x18\x05 \x01(\x03R\bsyncedAt\x12#\n" +
	"\rerror_message\x18\x06 \x01(\tR\ferrorMessage\"`\n" +
	"\x10MarkErrorRequest\x12'\n" +
	"\x0ftracking_number\x18\x01 \x01(\tR\x0etrackingNumber\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"G\n" +
	"\x11MarkErrorResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xe8\x01\n" +
	"\x0fTrackingService\x12C\n" +
	"\x0eUpsertTracking\x12\x17.tracking.UpsertRequest\x1a\x18.tracking.UpsertResponse\x12J\n" +
	"\vGetTracking\x12\x1c.tracking.GetTrackingRequest\x1a\x1d.tracking.GetTrackingResponse\x12D\n" +
	"\tMarkError\x12\x1a.tracking.MarkErrorRequest\x1a\x1b.tracking.MarkErrorResponseB\x17Z\x15tracking-srv/trackingb\x06proto3"

var (
	file_tracking_proto_rawDescOnce sync.Once
	file_tracking_proto_rawDescData []byte
)

func file_tracking_proto_rawDescGZIP() []byte {
	file_tracking_proto_rawDescOnce.Do(func() {
		file_tracking_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tracking_proto_rawDesc), len(file_tracking_proto_rawDesc)))
	})
	return file_tracking_proto_rawDescData
}

var file_tracking_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_tracking_proto_goTypes = []any{
	(*UpsertRequest)(nil),       // 0: tracking.UpsertRequest
	(*UpsertResponse)(nil),      // 1: tracking.UpsertResponse
	(*GetTrackingRequest)(nil),  // 2: tracking.GetTrackingRequest
	(*GetTrackingResponse)(nil), // 3: tracking.GetTrackingResponse
	(*MarkErrorRequest)(nil),    // 4: tracking.MarkErrorRequest
	(*MarkErrorResponse)(nil),   // 5: tracking.MarkErrorResponse
}
var file_tracking_proto_depIdxs = []int32{
	0, // 0: tracking.TrackingService.UpsertTracking:input_type -> tracking.UpsertRequest
	2, // 1: tracking.TrackingService.GetTracking:input_type -> tracking.GetTrackingRequest
	4, // 2: tracking.TrackingService.MarkError:input_type -> tracking.MarkErrorRequest
	1, // 3: tracking.TrackingService.UpsertTracking:output_type -> tracking.UpsertResponse
	3, // 4: tracking.TrackingService.GetTracking:output_type -> tracking.GetTrackingResponse
	5, // 5: tracking.TrackingService.MarkError:output_type -> tracking.MarkErrorResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tracking_proto_init() }
func file_tracking_proto_init() {
	if File_tracking_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tracking_proto_rawDesc), len(file_tracking_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tracking_proto_goTypes,
		DependencyIndexes: file_tracking_proto_depIdxs,
		MessageInfos:      file_tracking_proto_msgTypes,
	}.Build()
	File_tracking_proto = out.File
	file_tracking_proto_goTypes = nil
	file_tracking_proto_depIdxs = nil
}
